<!Doctype html>

<html>

<head>

<meta charset="UTF-8">
<meta name='viewport' content="width=device-width,initial-scale=1.0">

</head>

<body>
<?php include 'header.php';?>


<div class="container" style ="position: relative;"> 

        
    <div class="card">
     <video width="100%" autoplay muted loop id="myVideo">
  <source src="../function.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>
  <button id="myBtn" style ="width: 100px;
  font-size: 15px;
  padding: 5px;
  border: none;
  background: #000;
  color: #fff;
  cursor: pointer;position: absolute;
  top: 2%;left:10%;z-index:10;" onclick="myFunction()">Pause</button>
<br>
 <p>The fee for girls was specially kept as low as Rs. 60 per month for high school and Rs. 80 per month for Intermediate. This had an overwhelming response and number of enrollments increased every year thereafter as this fee could be afforded by the most backward and poor people of the village. The construction work started which was as per the regulations for getting affiliation from UP Board till High School and this was achieved in 2006, the first high school in the nearby area, which was further upgraded for affiliation of Intermediate in Arts stream in 2010.</p>
      
      <p>Manager  Mr. S. P. Shukla is a retired PCS Allied Officer, he provided 10 rooms for classes to be run, arranged 10 computers, a CD/DVD player and a Television for running smart classes for Science students of classes 9th and 10th with the help of electricity generated by the generator, arranged by him. To fill the excitement in the students, free school bags are being provided from 2012. Around 50 free sweaters are also given specially to the girls in the school every year. Every year on Independence day, three topper students are awarded. A new tradition of rewarding the retired teachers also started on Republic Day since 2016. The two teachers this year were Ramadhar Shukla and Ram Sanehi Yadav whose ages are between 80 to 90 years. They are the retired Headmasters of Primary School. A proposal for Science and Home Science for class 12th students has also been sent to the regional office which will be approved soon.</p>
    </div></div>

<?php include 'footer.php';?>
    <script>
var video = document.getElementById("myVideo");
var btn = document.getElementById("myBtn");

function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>

</body>


</html>
